name: Start MySQL container
description: Action of starting MySQL container

runs:
  using: "composite"
  steps:
    - name: Set up MySQL service
      shell: bash
      run: |
        docker run -d --name mysql -p 3306:3306 \
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes \
          -e MYSQL_DATABASE=blog \
          -e MYSQL_USER=user \
          -e MYSQL_PASSWORD=password \
          --health-cmd="mysqladmin ping -h localhost" \
          --health-interval=20s \
          --health-timeout=10s \
          --health-retries=10 \
          mysql:8

    - name: Wait for MySQL to be healthy
      shell: bash
      run: |
        set -e
        for i in {1..10}; do
          if docker inspect --format='{{.State.Health.Status}}' mysql | grep -q 'healthy'; then
            echo "MySQL is healthy!"
            break
          else
            echo "Waiting for MySQL to be healthy..."
            sleep 10
          fi
          if [ $i -eq 10 ]; then
            echo "MySQL is not healthy after waiting for 100 seconds."
            exit 1
          fi
        done

    - uses: actions/setup-go@v5
      with:
        go-version: "1.22"

    - uses: actions/checkout@v4

    - name: Migrate schema file
      shell: bash
      run: |
        curl -LO https://github.com/sqldef/sqldef/releases/download/v0.17.15/mysqldef_linux_386.tar.gz
        tar -zxvf mysqldef_linux_386.tar.gz
        ./mysqldef -u user -p password -h 127.0.0.1 -P 3306 blog < ./db/initdb.d/schema.sql
