version: "3"

services:
  # db:
  #   image: mysql:8.0.29
  #   platform: linux/amd64
  #   container_name: booked_db
  #   volumes:
  #     - ./db/initdb.d:/docker-entrypoint-initdb.d
  #     - ./db/conf.d/:/etc/mysql/conf.d
  #     - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
  #     - db-data:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_USER=user
  #     - MYSQL_PASSWORD=password
  #     - MYSQL_DATABASE=booked
  #   ports:
  #     - "3306:3306"
  frontend:
    container_name: blog_frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      API_URL: http://blog_backend:8080
    # depends_on:
    #   - db
  backend:
    container_name: blog_backend
    build:
      context: ./backend
      args:
        - target=dev
    ports:
      - "18000:8080"
    # depends_on:
    #   - db
  
# volumes:
#   db-data: