services:
  db:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name: blog_db
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d/:/etc/mysql/conf.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: blog
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    secrets:
      - mysql_root_password

  frontend:
    container_name: blog_frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      API_URL: http://blog_backend:8080
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]

  backend:
    container_name: blog_backend
    build:
      context: ./backend
      target: dev
    ports:
      - "18000:8080"
    develop:
      watch:
        - action: rebuild
          path: ./backend
    depends_on:
      db:
        condition: service_healthy
    command: ["go", "run", "."]

volumes:
  db-data:

secrets:
  mysql_root_password:
     file: db/mysql_root_password.txt
