name: Upload to S3
description: Action of uploading to S3

inputs:
  file_name:
    description: File name to be uploaded to S3
    required: true
  s3_bucket_name:
    description: S3 bucket name
    required: true
  s3_bucket_key:
    description: S3 key name
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload to S3
      shell: bash
      run: aws s3 cp ${{ inputs.file_name }} s3://${{ inputs.s3_bucket_name }}/${{ inputs.s3_bucket_key }} --recursive
