name: Execute SSM Run Command
description: Action of executing SSM Run Command

inputs:
  command-to-be-executed:
    description: Command to be executed
    required: true

runs:
  using: "composite"
  steps:
    - name: Execute command
      shell: bash
      run: |
        COMMAND="${{ inputs.command-to-be-executed }}"
        RESPONSE=$(eval "$COMMAND")
        echo "commandId=$(echo $RESPONSE | jq .Command.CommandId)" >> $GITHUB_ENV

    - name: Echo command ID
      shell: bash
      run: echo ${{ env.commandId }}
