name: Execute SSM Run Command
description: Action of executing SSM Run Command

inputs:
  command-to-be-executed:
    description: Command to be executed
    required: true

runs:
  using: "composite"
  steps:
    - name: Execute command
      shell: bash
      # Commands below extract Result of SSM Run Command
      run: |
        COMMAND_ID=$(${{ inputs.command-to-be-executed }} | jq --raw-output '.Command.CommandId')
        echo $COMMAND_ID
        aws ssm list-command-invocations --command-id ${COMMAND_ID} --details | jq '.CommandInvocations[].CommandPlugins[].Output'
