######################################
#
#  What:
#    - access AWS resources
#
#######################################

name: Access AWS Resources

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  s3ls:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oidc-role"

      - name: AWS CLI install
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - run: |
          IPV4=$(curl https://checkip.amazonaws.com)
          echo "IPV4=$IPV4" >> $GITHUB_ENV

      - name: Deploy
        run: |
          cat << EOF > memo
          Hello!
          This is memo.
          EOF
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ env.IPV4 }}/32
          echo "${{ secrets.PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key memo ${{ env.EC2_PUBLIC_DNS }}:/memo
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ env.IPV4 }}/32
        env:
          EC2_PUBLIC_DNS: ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }}
