######################################
#
#  What:
#    - access AWS resources
#
#######################################

name: Access AWS Resources

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  s3ls:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oidc-role"

      # Read S3
      - run: aws s3 ls s3://${{ secrets.S3_NAME }}
