name: Deploy to ECR

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

env:
  AWS_DEFAULT_REGION: ap-northeast-1
  ROLE_TO_ASSUME: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oidc-role-blog-deploy"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Build-Deploy
    steps:
      - uses: Kesin11/actions-timeline@v2
      - uses: actions/checkout@v4

      - name: 🔑 Setup AWS Credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}

      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: 🏗 Build, tag, and push image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: blog
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./backend
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
