name: EC2 auto deploy(frontend)

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd ./frontend
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd ./frontend && npm i
      - run: cd ./frontend && npm run build:prod
        env:
          ENV_IMAGE_URL: ${{ secrets.ENV_IMAGE_URL }}
          ENV_PROXY_API_URL: ${{ secrets.ENV_PROXY_API_URL }}
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./frontend/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Uses configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oidc-role"


      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Get IP Address
        run: |
          IPV4=$(curl https://checkip.amazonaws.com)
          echo "IPV4=$IPV4" >> $GITHUB_ENV

      - name: Deploy
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ env.IPV4 }}/32
          echo "${{ secrets.PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key index.html ${{ env.EC2_PUBLIC_DNS }}:/var/www/html
          scp -o StrictHostKeyChecking=no -i private_key -r assets ${{ env.EC2_PUBLIC_DNS }}:/var/www/html
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ env.IPV4 }}/32
        env:
          EC2_PUBLIC_DNS: ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }}
