name: greeting

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Check if it is worked'
        required: false
        default: true
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

env:
  script_path: $GITHUB_ACTION_PATH/actions

jobs:
  output_inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          ENVIRONMENT: ${{ inputs.environment }}

  hello:
    name: Say helloWorld when starting actions
    runs-on: ubuntu-latest

    steps:
      - name: Run hello.sh
        run: ${{ env.script_path }}/hello.sh
        shell: bash
      
      - name: Set Greeting
        run: echo "Hello $INPUT_TAGS."
        shell: bash
        env:
          INPUT_TAGS: ${{ inputs.tags }}

  goodbye:
    name: Say goodbye when starting actions
    runs-on: ubuntu-latest
        
    steps:
      - name: Run goodbye.sh
        run: ${{ env.script_path }}/goodbye.sh
        shell: bash
