name: Test (Backend)

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
      - name: Install dependencies
        run: cd backend && go get .
      - name: Build
        run: cd backend && go build -v ./...
      - name: Test with the Go CLI
        run: cd backend && go test -v ./...
