name: Uploaded Builded File (Backend)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/**

permissions:
  contents: write
  id-token: write

env:
  AWS_DEFAULT_REGION: ap-northeast-1
  ROLE_TO_ASSUME: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oidc-role-blog-deploy"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
    
      - name: Install dependencies
        run: cd backend && go get .

      - name: Build
        run: cd backend && go build

      - uses: actions/upload-artifact@v4
        with:
          name: blog
          path: backend/blog

  upload:
    runs-on: ubuntu-latest
    name: Upload to S3
    environment: production
    needs:
      - build
    steps:
      - uses: actions/checkout@v4

      - name: 🔑 Setup AWS Credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}

      - name: 🧪 install AWS CLI
        uses: ./.github/actions/install-aws-cli

      - uses: actions/download-artifact@v4
        with:
          path: blog

      - name: 🔥 Upload builded files to S3
        uses: ./.github/actions/upload-to-S3
        with:
          file_name: blog/blog
          s3_bucket_name: ${{ secrets.S3_BUCKET_NAME }}
          s3_bucket_key: blog
