name: Upload Builded Files (Frontend)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - frontend/**

permissions:
  contents: write
  id-token: write

env:
  AWS_DEFAULT_REGION: ap-northeast-1
  ROLE_TO_ASSUME: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oidc-role-blog-deploy"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Build
        run: cd frontend && npm run build:prod

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: frontend/dist

  upload:
    runs-on: ubuntu-latest
    name: Upload to S3
    environment: production
    needs:
      - build
    steps:
      - uses: actions/checkout@v4

      - name: 🔑 Setup AWS Credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}

      - name: 🧪 install AWS CLI
        uses: ./.github/actions/install-aws-cli

      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: 🔥 Upload builded files to S3
        uses: ./.github/actions/upload-to-S3
        with:
          file_name: dist/dist
          s3_bucket_name: ${{ secrets.S3_BUCKET_NAME }}
          s3_bucket_key: revision/dist
